### ISSUE TITLE
Disturbance in the Forwarder

### ISSUE THREAD

**Issue by aaronk** [birc-aeh/coalhmm#5]
Seems as though there has been a change in the **init** of the zipHMM Forwarder.  Doesn't take any arguments.

```
(coalhmm)[nedelman@builds examples]$ python estimate_example_ziphmm.py                                                                                      
Exception AttributeError: "'Forwarder' object has no attribute 'obj'" in <bound method Forwarder.__del__ of <pyZipHMM.pyZipHMM.Forwarder object at 0x2ae3438bfa10>> ignored
Traceback (most recent call last):
  File "estimate_example_ziphmm.py", line 112, in <module>
    f = Forwarder(seqFilename = foutname, nStates = len(modelI.tree_map), nObservables = 3)
TypeError: __init__() got an unexpected keyword argument 'nStates'
```

**Comment by aaronk** [comment]
Hi.  Any thoughts on this?

**Comment by mailund** [comment]
Hi, depending on which model you use of the CoalHMM you might want to use https://github.com/mailund/IMCoalHMM instead. That is the version we actively maintain. I don't know if @birc-aeh has changed anything in this repository recently, but the other should be up to date with the current version of ZipHMM.

**Comment by aaronk** [comment]
Great!  I'll give that a shot.

ajk
