### ISSUE TITLE
Confusions on analysis.sh file

### ISSUE THREAD

**Issue by MaoYafei** [birc-aeh/coalhmm#7]
Dear All,

I am trying to run the analysis.sh file in test_data. (commands and results looks below): 

> [ .....]$ bash analysis.sh 
> This script gives an example analysis of both isolation and
> isolation-with-migration models.
> 
> It first converts all alignments to the zipHMM format and then
> uses the analysis scripts to estimate parameters.
> 
> Converting isolation model files...
> python ../scripts/prepare-alignments.py I/sim_I_0.gz fasta analysis/sim_I_0.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_10.gz fasta analysis/sim_I_10.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_1.gz fasta analysis/sim_I_1.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_2.gz fasta analysis/sim_I_2.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_3.gz fasta analysis/sim_I_3.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_4.gz fasta analysis/sim_I_4.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_5.gz fasta analysis/sim_I_5.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_6.gz fasta analysis/sim_I_6.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_7.gz fasta analysis/sim_I_7.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_8.gz fasta analysis/sim_I_8.ziphmm
> python ../scripts/prepare-alignments.py I/sim_I_9.gz fasta analysis/sim_I_9.ziphmm
> Done.
> 
> Converting isolation-with-migration model files...
> python ../scripts/prepare-alignments.py IM/sim_IM_0.gz fasta analysis/sim_IM_0.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_1.gz fasta analysis/sim_IM_1.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_2.gz fasta analysis/sim_IM_2.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_3.gz fasta analysis/sim_IM_3.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_4.gz fasta analysis/sim_IM_4.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_5.gz fasta analysis/sim_IM_5.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_6.gz fasta analysis/sim_IM_6.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_7.gz fasta analysis/sim_IM_7.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_8.gz fasta analysis/sim_IM_8.ziphmm
> python ../scripts/prepare-alignments.py IM/sim_IM_9.gz fasta analysis/sim_IM_9.ziphmm
> Done.
> 
> 
> ANALYSIS OF I DATA
> 
> Analyse I data with I model.
> python ../scripts/estimate-using-I-model.py --verbose --header --out=I-results-I.txt analysis/sim_I_0.ziphmm analysis/sim_I_10.ziphmm analysis/sim_I_1.ziphmm analysis/sim_I_2.ziphmm analysis/sim_I_3.ziphmm analysis/sim_I_4.ziphmm analysis/sim_I_5.ziphmm analysis/sim_I_6.ziphmm analysis/sim_I_7.ziphmm analysis/sim_I_8.ziphmm analysis/sim_I_9.ziphmm
> Loading forwarders... done
> Constructing model... done
> Optimization terminated successfully.
>          Current function value: 708577.290859
>          Iterations: 210
>          Function evaluations: 386
> 
> Analyse I data with IM model.
> python ../scripts/estimate-using-IM-model.py --verbose --header --out=I-results-IM.txt analysis/sim_I_0.ziphmm analysis/sim_I_10.ziphmm analysis/sim_I_1.ziphmm analysis/sim_I_2.ziphmm analysis/sim_I_3.ziphmm analysis/sim_I_4.ziphmm analysis/sim_I_5.ziphmm analysis/sim_I_6.ziphmm analysis/sim_I_7.ziphmm analysis/sim_I_8.ziphmm analysis/sim_I_9.ziphmm
> Loading forwarders... done
> Constructing model... done
> Warning: Maximum number of function evaluations has been exceeded.
> 
> 
> ANALYSIS OF IM DATA
> 
> Analyse IM data with I model.
> python ../scripts/estimate-using-I-model.py --verbose --header --out=IM-results-I.txt analysis/sim_IM_0.ziphmm analysis/sim_IM_1.ziphmm analysis/sim_IM_2.ziphmm analysis/sim_IM_3.ziphmm analysis/sim_IM_4.ziphmm analysis/sim_IM_5.ziphmm analysis/sim_IM_6.ziphmm analysis/sim_IM_7.ziphmm analysis/sim_IM_8.ziphmm analysis/sim_IM_9.ziphmm
> Loading forwarders... done
> Constructing model... done
> Optimization terminated successfully.
>          Current function value: 611941.212104
>          Iterations: 168
>          Function evaluations: 318
> 
> Analyse IM data with IM model.
> python ../scripts/estimate-using-IM-model.py --verbose --header --out=IM-results-IM.txt analysis/sim_IM_0.ziphmm analysis/sim_IM_1.ziphmm analysis/sim_IM_2.ziphmm analysis/sim_IM_3.ziphmm analysis/sim_IM_4.ziphmm analysis/sim_IM_5.ziphmm analysis/sim_IM_6.ziphmm analysis/sim_IM_7.ziphmm analysis/sim_IM_8.ziphmm analysis/sim_IM_9.ziphmm
> Loading forwarders... done
> Constructing model... done
> Optimization terminated successfully.
>          Current function value: 612229.096809
>          Iterations: 549
>          Function evaluations: 979
> 
> 
> Model checking for isolation model:
> I AIC = 1417160.581718, IM AIC = 1417170.944708, DeltaAIC = 3.181495
> 
> Model checking for migration model:
> I AIC = 1223888.424208, IM AIC = 1224468.193618, DeltaAIC = 287.884705

Get the output files below:

```
I-results-I.txt : 
logL    T       C       R
-708577.290859  0.00559601734119        461.479659005   0.196009468576
I-results-IM.txt:
logL    Tmig    Tsplit  M       C       R
-708580.472354  8.18859630449e-08       0.00383937957225        0.499022129704  446.056710799   0.187944044217
```
----------------------------------------

```
IM-results-I.txt 
logL    T       C       R
-611941.212104  0.00517488391589        474.173901339   0.244592606841
IM-results-IM.txt
logL    Tmig    Tsplit  M       C       R
-612229.096809  5.60159828403e-13       0.00299675787448        0.394026800695  366.913501158   0.0756575584109
```
-------------------------------------------------------
Codes from analysis.sh for AIC calculation:

> echo "Model checking for isolation model:"
> IlogL=`tail -n 1 I-results-I.txt | cut -f1`
> IMlogL=`tail -n 1 I-results-IM.txt | cut -f1`
> IAIC=`bc -q <( echo "2 * (3 - $IlogL)"  ; echo quit )`
> IMAIC=`bc -q <( echo "2 * (5 - $IMlogL)"  ; echo quit )`
> Delta=`bc -q <( echo $IlogL - $IMlogL ; echo quit )`
> 
> echo "I AIC = $IAIC, IM AIC = $IMAIC, DeltaAIC = $Delta"
> echo
> 
> echo "Model checking for migration model:"
> 
> IlogL=`tail -n 1 IM-results-I.txt | cut -f1`
> IMlogL=`tail -n 1 IM-results-IM.txt | cut -f1`
> IAIC=`bc -q <( echo "2 * (3 - $IlogL)"  ; echo quit )`
> IMAIC=`bc -q <( echo "2 * (5 - $IMlogL)"  ; echo quit )`
> Delta=`bc -q <( echo $IlogL - $IMlogL ; echo quit )`
> 
> echo "I AIC = $IAIC, IM AIC = $IMAIC, DeltaAIC = $Delta"
> echo
------------------------------------------------------------------------------------

Question1:  in analysis.sh file, DeltaAIC is calculated as  

> Delta=`bc -q <( echo $IlogL - $IMlogL ; echo quit )`

but I think it should be calculated as 

> Delta=`bc -q <( echo $IAIC - $IMAIC ; echo quit )`, right?

------------------------------------------------------------------------------------

Question2: for AIC analysis, usually, the lower AIC represents the better model. 
So, for I dataset, the AIC of I model (1417160(I)<1417170(IM)) is lower suggesting Isolation model is better. 
for IM dataset, the AIC of I model (1223888(I)<1224468(IM)) is lower suggesting Isolation model is better. (but expect isolation with migration (IM) model is better for IM dataset). Do you think anything wrong for my understanding or my running or dataset?

------------------------------------------------------------------------------------
Question3: if we assumed: Delta=`bc -q <( echo $IAIC - $IMAIC ; echo quit )`. so Delta is much greater than 0 suggesting isolation with migration (IM) model is better. right? but if we assume Delta=`bc -q <( echo $IlogL - $IMlogL ; echo quit )`, if Delta is much greater than 0 suggesting isolation model (I) is better. 

However, in the manuscript fig 11, "Negative values indicate a preference for the isolation model while positive values indicate a preference for the isolation-with-migration model. " (Mailund, Thomas, et al. "A new isolation with migration model along complete genomes infers very different divergence processes among closely related great ape species." PLoS genetics 8.12 (2012): e1003125.). 
I am wondering that the how do you calculate DeltaAIC in the manuscript? is it different from the example (analysis.sh)?

Thanks a lot and looking forward to your reply.

Best, 
Yafei

**Comment by mailund** [comment]
1) You are right.

2) This does look like the model preferred the I model over the IM on IM data, but there is some statistical uncertainty for shorter sequences, so you should only be worried if this happens consistently (or just more often than not). That is not what we observed when we tested the software, but there might have been bugs introduced since then, so let me know if the problem persists.

3) I think we have just flipped the signs in the manuscript. We didn't use this script in the experiments there. The smaller AIC is the preferred model, so for IAIC - IMAIC, negative means I is preferred and positive means IM is preferred.

**Comment by mailund** [comment]
BTW, you might want to check out https://github.com/mailund/IMCoalHMM -- that is the version of the CoalHMM we are actively developing and using now. This repository is an older version. We simplified the code somewhat by sticking to pairwise alignments and that allowed us to make a nicer implementation.

**Comment by MaoYafei** [comment]
Hi Mailund, 

Thanks again. 

According to my preliminary results, I think your software is pretty good and the results generated by CoalHMM is consistent with ABBA-BABA test and Phylonetwork methods. Also, I will try your new version. 
Thanks a lot!

Best, 
Yafei
